version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - pip3 install -r requirements.txt
      - python3 app.py &
artifacts:
  files: '**/*'
  discard-paths: yes
